const TYPES = {
    LOAD: 'LOAD_DATA',
    LOAD_SERVICE_ITEM: 'LOAD_SERVICE_ITEM',
    LOAD_SERVICE_EXTRA: 'LOAD_SERVICE_EXTRA',
    USER_SELECT_SERVICE: 'USER_SELECT_SERVICE',
    ADD_TO_CART: 'ADD_TO_CART'
}
export { TYPES }